# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 751, 381))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.InsertTrail = QtWidgets.QWidget()
        self.InsertTrail.setObjectName("InsertTrail")
        self.parkInput = QtWidgets.QComboBox(self.InsertTrail)
        self.parkInput.setGeometry(QtCore.QRect(70, 130, 201, 22))
        self.parkInput.setObjectName("parkInput")
        self.label_8 = QtWidgets.QLabel(self.InsertTrail)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.InsertTrail)
        self.label_6.setGeometry(QtCore.QRect(170, 170, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.InsertTrail)
        self.label_7.setGeometry(QtCore.QRect(150, 210, 101, 16))
        self.label_7.setObjectName("label_7")
        self.timeInput = QtWidgets.QSpinBox(self.InsertTrail)
        self.timeInput.setGeometry(QtCore.QRect(220, 250, 42, 22))
        self.timeInput.setObjectName("timeInput")
        self.summInput = QtWidgets.QTextEdit(self.InsertTrail)
        self.summInput.setGeometry(QtCore.QRect(280, 50, 331, 291))
        self.summInput.setObjectName("summInput")
        self.label_4 = QtWidgets.QLabel(self.InsertTrail)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.InsertTrail)
        self.label_10.setGeometry(QtCore.QRect(170, 250, 41, 16))
        self.label_10.setObjectName("label_10")
        self.regionInput = QtWidgets.QComboBox(self.InsertTrail)
        self.regionInput.setGeometry(QtCore.QRect(70, 90, 201, 22))
        self.regionInput.setObjectName("regionInput")
        self.gradInput = QtWidgets.QSpinBox(self.InsertTrail)
        self.gradInput.setGeometry(QtCore.QRect(90, 210, 42, 22))
        self.gradInput.setMaximum(5)
        self.gradInput.setObjectName("gradInput")
        self.starInput = QtWidgets.QSpinBox(self.InsertTrail)
        self.starInput.setGeometry(QtCore.QRect(220, 170, 42, 22))
        self.starInput.setMaximum(5)
        self.starInput.setObjectName("starInput")
        self.label = QtWidgets.QLabel(self.InsertTrail)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.InsertTrail)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 101, 16))
        self.label_9.setObjectName("label_9")
        self.diffInput = QtWidgets.QSpinBox(self.InsertTrail)
        self.diffInput.setGeometry(QtCore.QRect(110, 170, 42, 22))
        self.diffInput.setMaximum(5)
        self.diffInput.setObjectName("diffInput")
        self.surfInput = QtWidgets.QSpinBox(self.InsertTrail)
        self.surfInput.setGeometry(QtCore.QRect(220, 210, 42, 22))
        self.surfInput.setMaximum(5)
        self.surfInput.setObjectName("surfInput")
        self.label_3 = QtWidgets.QLabel(self.InsertTrail)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_3.setObjectName("label_3")
        self.lenInput = QtWidgets.QSpinBox(self.InsertTrail)
        self.lenInput.setGeometry(QtCore.QRect(90, 250, 42, 22))
        self.lenInput.setObjectName("lenInput")
        self.lineEdit = QtWidgets.QLineEdit(self.InsertTrail)
        self.lineEdit.setGeometry(QtCore.QRect(110, 50, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_11 = QtWidgets.QLabel(self.InsertTrail)
        self.label_11.setGeometry(QtCore.QRect(280, 20, 72, 15))
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(self.InsertTrail)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.InsertTrail)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 101, 16))
        self.label_5.setObjectName("label_5")
        self.subBtn = QtWidgets.QPushButton(self.InsertTrail)
        self.subBtn.setGeometry(QtCore.QRect(620, 20, 121, 321))
        self.subBtn.setObjectName("subBtn")
        self.label_12 = QtWidgets.QLabel(self.InsertTrail)
        self.label_12.setGeometry(QtCore.QRect(10, 290, 101, 16))
        self.label_12.setObjectName("label_12")
        self.tIDInput = QtWidgets.QLineEdit(self.InsertTrail)
        self.tIDInput.setGeometry(QtCore.QRect(110, 290, 161, 21))
        self.tIDInput.setObjectName("tIDInput")
        self.tabWidget.addTab(self.InsertTrail, "")
        self.InsertRes = QtWidgets.QWidget()
        self.InsertRes.setObjectName("InsertRes")
        self.label_13 = QtWidgets.QLabel(self.InsertRes)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.InsertRes)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 72, 15))
        self.label_14.setObjectName("label_14")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.InsertRes)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 50, 201, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.parkInput_2 = QtWidgets.QComboBox(self.InsertRes)
        self.parkInput_2.setGeometry(QtCore.QRect(90, 80, 201, 22))
        self.parkInput_2.setObjectName("parkInput_2")
        self.label_15 = QtWidgets.QLabel(self.InsertRes)
        self.label_15.setGeometry(QtCore.QRect(30, 80, 41, 16))
        self.label_15.setObjectName("label_15")
        self.yearInput = QtWidgets.QDateEdit(self.InsertRes)
        self.yearInput.setGeometry(QtCore.QRect(90, 120, 110, 22))
        self.yearInput.setObjectName("yearInput")
        self.label_16 = QtWidgets.QLabel(self.InsertRes)
        self.label_16.setGeometry(QtCore.QRect(30, 120, 41, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.InsertRes)
        self.label_17.setGeometry(QtCore.QRect(20, 160, 61, 21))
        self.label_17.setObjectName("label_17")
        self.resInput = QtWidgets.QSpinBox(self.InsertRes)
        self.resInput.setGeometry(QtCore.QRect(90, 160, 101, 22))
        self.resInput.setObjectName("resInput")
        self.label_18 = QtWidgets.QLabel(self.InsertRes)
        self.label_18.setGeometry(QtCore.QRect(20, 200, 61, 21))
        self.label_18.setObjectName("label_18")
        self.injInput = QtWidgets.QSpinBox(self.InsertRes)
        self.injInput.setGeometry(QtCore.QRect(90, 200, 101, 22))
        self.injInput.setObjectName("injInput")
        self.label_19 = QtWidgets.QLabel(self.InsertRes)
        self.label_19.setGeometry(QtCore.QRect(20, 240, 61, 21))
        self.label_19.setObjectName("label_19")
        self.deathInput = QtWidgets.QSpinBox(self.InsertRes)
        self.deathInput.setGeometry(QtCore.QRect(90, 240, 101, 22))
        self.deathInput.setObjectName("deathInput")
        self.pushButton = QtWidgets.QPushButton(self.InsertRes)
        self.pushButton.setGeometry(QtCore.QRect(300, 30, 401, 261))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.InsertRes, "")
        self.tSearch = QtWidgets.QWidget()
        self.tSearch.setObjectName("tSearch")
        self.label_20 = QtWidgets.QLabel(self.tSearch)
        self.label_20.setGeometry(QtCore.QRect(30, 10, 161, 31))
        self.label_20.setObjectName("label_20")
        self.tIDin = QtWidgets.QLineEdit(self.tSearch)
        self.tIDin.setGeometry(QtCore.QRect(190, 20, 271, 21))
        self.tIDin.setObjectName("tIDin")
        self.searchBtn = QtWidgets.QPushButton(self.tSearch)
        self.searchBtn.setGeometry(QtCore.QRect(480, 10, 251, 201))
        self.searchBtn.setObjectName("searchBtn")
        self.trailShow = QtWidgets.QTextBrowser(self.tSearch)
        self.trailShow.setGeometry(QtCore.QRect(30, 60, 441, 251))
        self.trailShow.setObjectName("trailShow")
        self.delBtn = QtWidgets.QPushButton(self.tSearch)
        self.delBtn.setGeometry(QtCore.QRect(530, 230, 151, 71))
        self.delBtn.setObjectName("delBtn")
        self.tabWidget.addTab(self.tSearch, "")
        self.rSearch = QtWidgets.QWidget()
        self.rSearch.setObjectName("rSearch")
        self.rIDin = QtWidgets.QLineEdit(self.rSearch)
        self.rIDin.setGeometry(QtCore.QRect(180, 20, 271, 21))
        self.rIDin.setObjectName("rIDin")
        self.label_21 = QtWidgets.QLabel(self.rSearch)
        self.label_21.setGeometry(QtCore.QRect(0, 10, 171, 31))
        self.label_21.setObjectName("label_21")
        self.delBtn_2 = QtWidgets.QPushButton(self.rSearch)
        self.delBtn_2.setGeometry(QtCore.QRect(520, 230, 151, 71))
        self.delBtn_2.setObjectName("delBtn_2")
        self.rescueShow = QtWidgets.QTextBrowser(self.rSearch)
        self.rescueShow.setGeometry(QtCore.QRect(20, 60, 441, 251))
        self.rescueShow.setObjectName("rescueShow")
        self.searchBtn_2 = QtWidgets.QPushButton(self.rSearch)
        self.searchBtn_2.setGeometry(QtCore.QRect(470, 10, 251, 201))
        self.searchBtn_2.setObjectName("searchBtn_2")
        self.tabWidget.addTab(self.rSearch, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.completeMsg = QtWidgets.QMessageBox()
        self.completeMsg.setText('Complete')

        self.searchBtn.clicked.connect(self.trailQurey)
        self.delBtn.clicked.connect(self.trailDel)
        self.delBtn.setStyleSheet('background-color: red;')
        self.delBtn_2.setStyleSheet('background-color: red;')
        self.searchBtn_2.clicked.connect(self.resQurey)
        self.delBtn_2.clicked.connect(self.resDel)
        self.subBtn.clicked.connect(self.submit_insertTrail)
        self.pushButton.clicked.connect(self.submit_insertRes)
        self.load_data()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "gradient"))
        self.label_6.setText(_translate("MainWindow", "star"))
        self.label_7.setText(_translate("MainWindow", "surface"))
        self.label_4.setText(_translate("MainWindow", "Park"))
        self.label_10.setText(_translate("MainWindow", "time"))
        self.label.setText(_translate("MainWindow", "Insert a new trail"))
        self.label_9.setText(_translate("MainWindow", "length"))
        self.label_3.setText(_translate("MainWindow", "Region"))
        self.label_11.setText(_translate("MainWindow", "summary"))
        self.label_2.setText(_translate("MainWindow", "Trial Name"))
        self.label_5.setText(_translate("MainWindow", "difficulty"))
        self.subBtn.setText(_translate("MainWindow", "Submit"))
        self.label_12.setText(_translate("MainWindow", "Trial ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InsertTrail), _translate("MainWindow", "Insert Trail"))
        self.label_13.setText(_translate("MainWindow", "Insert New Rescure"))
        self.label_14.setText(_translate("MainWindow", "Rescue ID"))
        self.label_15.setText(_translate("MainWindow", "Park"))
        self.yearInput.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.label_16.setText(_translate("MainWindow", "year"))
        self.label_17.setText(_translate("MainWindow", "Rescued"))
        self.label_18.setText(_translate("MainWindow", "Injury"))
        self.label_19.setText(_translate("MainWindow", "Death"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InsertRes), _translate("MainWindow", "Insert Rescure"))
        self.label_20.setText(_translate("MainWindow", "Search by Trail ID"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.delBtn.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tSearch), _translate("MainWindow", "Search or Del Trail"))
        self.label_21.setText(_translate("MainWindow", "Search by Rescure ID"))
        self.delBtn_2.setText(_translate("MainWindow", "Delete"))
        self.searchBtn_2.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rSearch), _translate("MainWindow", "Search or Del Rescue"))

    def load_data(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()

        # 执行 SQL
        cursor.execute("""
            SELECT p.park_name
            FROM Park as p
        """)
        row = cursor.fetchall()
        conn.close()
        self.parkInput.addItems([item[0] for item in row])
        self.parkInput_2.addItems([item[0] for item in row])
        self.regionInput.addItems(['Central New Territories','Hong Kong Island','Lantau','North New Territories','Sai Kung','West New Territories'])

    def submit_insertTrail(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()

        #获取路径id、名字、地区、公园、难度、评价、坡度、路面、长度、时间、简介
        tID = self.tIDInput.text()
        tName = self.lineEdit.text()
        tRegion = self.regionInput.currentText()
        tPark = self.parkInput.currentText()
        tDiff = self.diffInput.value()
        tStar = self.starInput.value()
        tGrad = self.gradInput.value()
        tSurf = self.surfInput.value()
        tLen = self.lenInput.value()
        tTime = self.timeInput.value()
        tSumm = self.summInput.toPlainText()
        #取得PID
        cursor.execute("""
            SELECT p.park_id
            FROM Park as p
            WHERE park_name = ?
        """,((tPark),))
        pID = cursor.fetchone()

        cursor.execute('''INSERT INTO Trail (trail_id, park_id, trail_name, region, difficulty, star, surface, gradient, length, time, summary)
                          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''', (tID,pID[0],tName,tRegion,tDiff,tStar,tSurf,tGrad,tLen,tTime,tSumm,))

        conn.commit()
        conn.close()

        self.completeMsg.exec_()
    
    def submit_insertRes(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()

        #获取ResID, parkID,year,rescued,injury,death
        rID = self.lineEdit_2.text()
        rPark = self.parkInput_2.currentText()
        rYear = self.yearInput.date().toString('yyyy')
        rRes = self.resInput.value()
        rInj = self.injInput.value()
        rDeath = self.deathInput.value()
        #取得PID
        cursor.execute("""
            SELECT p.park_id
            FROM Park as p
            WHERE park_name = ?
        """,((rPark),))
        rPID = cursor.fetchone()

        cursor.execute('''INSERT INTO Rescue (rescue_id, park_id, year, rescue_count, injury_count, death_count)
                          VALUES (?, ?, ?, ?, ?, ?)''', (rID,rPID[0],rYear,rRes,rInj,rDeath,))

        conn.commit()
        conn.close()

        self.completeMsg.exec_()

    def trailQurey(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()
        #get tID input
        tID = self.tIDin.text()
        cursor.execute("""
            SELECT t.trail_name, p.park_name, t.region, t.difficulty, t.length, t.time, t.star
            FROM Trail t
            JOIN Park p ON t.park_id = p.park_id
            WHERE t.trail_id = ?
        """,(tID,))
        row = cursor.fetchone()
        conn.close()
        if row == None:
            resultText = 'Result not found'
        else:
            resultText = "Trail Name: {}\n".format(row[0])+"Park Name:{}\n".format(row[1])+"Region:{}\n".format(row[2])+"Difficulty:{} star(s)\n".format(row[3])+"Length:{} Km\n".format(row[4])+"Duration:{} hour(s)\n".format(row[5])+"Recommanded:{} star(s)\n".format(row[6])
        self.trailShow.setText(resultText)

    def trailDel(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()
        #get tID input
        tID = self.tIDin.text()
        cursor.execute("""
            DELETE FROM Trail
            WHERE trail_id = ?
        """,(tID,))

        conn.commit()
        conn.close()
        self.completeMsg.exec_()

    def resQurey(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()
        #get rID input
        rID = self.rIDin.text()
        cursor.execute("""
            SELECT p.park_name, r.year, r.rescue_count, r.injury_count, r.death_count
            FROM Rescue as r
            JOIN Park p ON r.park_id = p.park_id
            WHERE r.rescue_id = ?
        """,(rID,))
        row = cursor.fetchone()
        conn.close()
        if row == None:
            resultText = 'Result not found'
        else:
            resultText = "Located Park: {}\n".format(row[0])+"Year:{}\n".format(row[1])+"Rescue count:{}\n".format(row[2])+"Injury count:{}\n".format(row[3])+"Death count:{}\n".format(row[4])
        self.rescueShow.setText(resultText)

    def resDel(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()
        #get rID input
        rID = self.rIDin.text()
        cursor.execute("""
            DELETE FROM Rescue
            WHERE rescue_id = ?
        """,(rID,))

        conn.commit()
        conn.close()
        self.completeMsg.exec_()