# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\learn\BigData\pj\hiking\qurey.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 331, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 20, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 60, 441, 481))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 463, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.load_data() #加载数据
        self.pushButton.clicked.connect(self.show_text)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "查询路径信息"))
        self.pushButton.setText(_translate("MainWindow", "查找"))

    def load_data(self):
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()

        # 执行 SQL
        cursor.execute("""
            SELECT t.trail_name
            FROM Trail t
        """)
        row = cursor.fetchall()
        conn.close()
        self.comboBox.addItems([item[0] for item in row])

    def show_text(self):
        selected_item = self.comboBox.currentText()
        import sqlite3
        from sqlite3 import Error
        try:
            conn = sqlite3.connect('data/hiking.db')
        except Error as e:
            print(e)
    
        cursor = conn.cursor()

        # 执行 SQL
        cursor.execute("""
            SELECT t.trail_name, p.park_name, t.region, t.difficulty, t.length, t.time, t.star
            FROM Trail t
            JOIN Park p ON t.park_id = p.park_id
            WHERE t.trail_name = ?
        """,(selected_item,))
        row = cursor.fetchone()
        conn.close()

        self.textBrowser.setText("Trail Name: {}\n".format(row[0])+"Park Name:{}\n".format(row[1])+"Region:{}\n".format(row[2])+"Difficulty:{} star(s)\n".format(row[3])+"Length:{} Km\n".format(row[4])+"Duration:{} hour(s)\n".format(row[5])+"Recommanded:{} star(s)\n".format(row[6]))